version: '3'
services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
